[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
rock_paper_scissors = "877CES5Ju3qoQJTCFqokCjcqjR6sFHEstfnqjqmvSXo4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kevin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
