[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
rock_paper_scissors = "rock7uz5eZdz8fb1ZEfZ1aR428ncvkYBrgebwyzaqBG"
[programs.devnet]
rock_paper_scissors = "rock7uz5eZdz8fb1ZEfZ1aR428ncvkYBrgebwyzaqBG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./rpstBRQkjzHZhsJKL6ENJXicc6nq2x49pDq7iTSRmuD.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
